### ISSUE TITLE
Make changings according to folder structure 

### ISSUE THREAD

**Issue by bilal42011** [bilal42011/Fyp-Frontend#7]
### **Changes to be made in  src/pages folder**

**Searchresultspage and signup page are still inside folders make them according to folder structure**

Pages folder will only contain page.js files not folders

**Comment by msafwankarim** [comment]
acha 😁

**Comment by bilal42011** [comment]
> acha 😁

It is a professional project our medium of instructions are in English!!

**Comment by bilal42011** [comment]
Next time it will not be tolerated!
And let me know here in the comments as soon as you resolved the issue.
Thanks!

**Comment by msafwankarim** [comment]
Ok thanks
https://www.youtube.com/watch?v=5rzdwq78qWc

**Comment by bilal42011** [comment]
### **I have seen video I felt so motivated and resolved the issue ...**

**Now in pages directory searchresults page and signup page are in root and removed from their folders..... also empty searchresults.module.css file has been deleted ....now pages directory only contain direct files just according to folder structure specified by me!**

_But keep in mind components directory is still not according to folder structure .... will create separate issue for that!_

**Changed done in the following commit. Thankyou!**
https://github.com/bilal42011/Fyp-Frontend/commit/652e62c0ed9fa5086c9cd85374a1c6c78ee13b3c
