### ISSUE TITLE
Making User Profile Description Component resuable

### ISSUE THREAD

**Issue by bilal42011** [bilal42011/Fyp-Frontend#9]
### **Have to make Reusable Component used for displaying User Profile Description **

**This implementation is defined in UserProfile.js page which is in the src/pages folder.**

_Have to extract relevant profile description code in the described above file and also have to make a separate reusable component in the Components folder for it so that it can be used in different pages later on and will make it easier for Devs to use.!!_

Thankyou!!

**Comment by ThienBNguyen** [comment]
Hi, I am interested in the issue.

**Comment by bilal42011** [comment]
> Hi, I am interested in the issue.

Bro thanks for reaching out ... actually it is our university FYP for final semester. I want to open source it but till 15 august only me and [@msafwankarim ](url) can work on it  so that things get right till its submission but after that Iwill inform you.
My plan is to enhance this project soon ...actually its an  Ecommerce platform for customized products.
Will let you know on 15th august and collaborate together !! Thanks for you interest!!

**Comment by bilal42011** [comment]
Will soon open it for everybody to contribute!

**Comment by ThienBNguyen** [comment]
I have clone your repo. the project looks great. you have some static data object inside component. it would be better to for your component if place those static object inside a datasource.js file and export it.

**Comment by bilal42011** [comment]
> I have clone your repo. the project looks great. you have some static data object inside component. it would be better to for your component if place those static object inside a datasource.js file and export it.

That's cool bro...Yes you are absolutely right but this is for demonstration only we would replace them backend endpoints that are still to be created for that we will use Node.js/Express.js and MongoDB!
Bro you can join us start working on it if you are interested I will assign you some task! ?
Thanks

**Comment by bilal42011** [comment]
We are still left with some pages that are to be developed it will be great if you contribute to this project!!

**Comment by ThienBNguyen** [comment]
which task that you need help with?

**Comment by bilal42011** [comment]
Bro we decided to wait till 15th august after that we can collaborate!
